name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build src/Basic/ScfPackageSources.Basic.sln --configuration Release

 #   - name: Publish NuGet
 #     uses: rohith/publish-nuget@v2.0.0
 #     with:
 #       # Filepath of the project to be packaged, relative to root of repository
 #       PROJECT_FILE_PATH: /**/*.csproj
